# Generated by Django 3.2 on 2021-04-28 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='details',
            new_name='body',
        ),
    ]
